services:
  # linux/arm64/v8
  ubuntu-linux-arm64-v8:
    image: ubuntu@sha256:a3f23b6e99cee41b8fffbd8a22d75728bb1f06af30fc79f533f27c096eda8993
    platform: linux/arm64
    stdin_open: true
    tty: true

  # # linux/ppc64le
  # ubuntu-linux-ppc64le:
  #   image: ubuntu@
  # # linux/riscv64
  # ubuntu-linux-riscv64:
  #   image: ubuntu@
  # # linux/s390x
  # ubuntu-linux-s390x:
  #   image: ubuntu@
  # # linux/amd64
  # ubuntu-linux-amd64:
  #   image: ubuntu@
  # # linux/arm/v7
  # ubuntu-linux-arm-v7:
  #   image: ubuntu@





